// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6xmC7aGXLhatCnDQuo7DEVne4FztAuL4',
    appId: '1:125592510245:web:f226f5a848330a9a7844cc',
    messagingSenderId: '125592510245',
    projectId: 'ase456-29a2a',
    authDomain: 'ase456-29a2a.firebaseapp.com',
    storageBucket: 'ase456-29a2a.firebasestorage.app',
    measurementId: 'G-DW4MV93ME2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7l30Y65K3UzafwGsUr0xpRDHhFeSMlSA',
    appId: '1:125592510245:android:29585aaad41243c87844cc',
    messagingSenderId: '125592510245',
    projectId: 'ase456-29a2a',
    storageBucket: 'ase456-29a2a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6xmC7aGXLhatCnDQuo7DEVne4FztAuL4',
    appId: '1:125592510245:web:11ef85a0b6d76dba7844cc',
    messagingSenderId: '125592510245',
    projectId: 'ase456-29a2a',
    authDomain: 'ase456-29a2a.firebaseapp.com',
    storageBucket: 'ase456-29a2a.firebasestorage.app',
    measurementId: 'G-QQ23VYX71J',
  );
}
